wandb: WARNING The save_model argument by default saves the model in the HDF5 format that cannot save custom objects like subclassed models and custom layers. This behavior will be deprecated in a future release in favor of the SavedModel format. Meanwhile, the HDF5 model is saved as W&B files and the SavedModel as W&B Artifacts.
WARNING:tensorflow:Callback method `on_train_batch_end` is slow compared to the batch time (batch time: 0.0017s vs `on_train_batch_end` time: 0.0026s). Check your callbacks.
wandb: Adding directory to artifact (C:\MyDocuments\Disertatie\segments\wandb_visualization\overlap\wandb\run-20230424_201914-ecdxga8k\files\model-best)... Done. 0.0s
Epoch 1/150
117/122 [===========================>..] - ETA: 0s - loss: 0.0302 - mae: 0.0499 - mse: 0.0053
122/122 [==============================] - 2s 10ms/step - loss: 0.0292 - mae: 0.0495 - mse: 0.0052 - val_loss: 0.0028 - val_mae: 0.0379 - val_mse: 0.0020 - lr: 0.0993
Epoch 2/150
 70/122 [================>.............] - ETA: 0s - loss: 0.0025 - mae: 0.0378 - mse: 0.0021
122/122 [==============================] - 1s 8ms/step - loss: 0.0024 - mae: 0.0373 - mse: 0.0020 - val_loss: 0.0023 - val_mae: 0.0390 - val_mse: 0.0022 - lr: 0.0993
Epoch 3/150
113/122 [==========================>...] - ETA: 0s - loss: 0.0020 - mae: 0.0347 - mse: 0.0017
122/122 [==============================] - 1s 7ms/step - loss: 0.0020 - mae: 0.0345 - mse: 0.0017 - val_loss: 0.0017 - val_mae: 0.0309 - val_mse: 0.0014 - lr: 0.0993
Epoch 4/150
122/122 [==============================] - 0s 1ms/step - loss: 0.0017 - mae: 0.0312 - mse: 0.0015 - val_loss: 0.0019 - val_mae: 0.0322 - val_mse: 0.0015 - lr: 0.0993
Epoch 5/150
115/122 [===========================>..] - ETA: 0s - loss: 0.0016 - mae: 0.0295 - mse: 0.0013
122/122 [==============================] - 1s 7ms/step - loss: 0.0016 - mae: 0.0294 - mse: 0.0013 - val_loss: 0.0014 - val_mae: 0.0267 - val_mse: 0.0011 - lr: 0.0993
Epoch 6/150
108/122 [=========================>....] - ETA: 0s - loss: 0.0015 - mae: 0.0278 - mse: 0.0012
122/122 [==============================] - 1s 7ms/step - loss: 0.0015 - mae: 0.0276 - mse: 0.0012 - val_loss: 0.0013 - val_mae: 0.0266 - val_mse: 0.0011 - lr: 0.0993
Epoch 7/150
114/122 [===========================>..] - ETA: 0s - loss: 0.0016 - mae: 0.0284 - mse: 0.0013
Traceback (most recent call last):
  File "C:\MyDocuments\Disertatie\segments\wandb_visualization\overlap\wrapper_test_and_train.py", line 80, in <module>
    train_models_and_save(n_members,data,test_size,train_group, epochs, batch_size, learning_rate,optimizer,hidden_layer_size,patience,monitor)
  File "C:\MyDocuments\Disertatie\segments\wandb_visualization\overlap\test_and_train.py", line 21, in train_models_and_save
    network, history = train_model_sweep(build_nn_sweep(optimizer, learning_rate, hidden_layer_size), x_train,
  File "C:\MyDocuments\Disertatie\segments\model_training\overlap\model_generating.py", line 199, in train_model_sweep
    history = network.fit(x_train, y_train, epochs=epochs, batch_size = batch_size, validation_data=(x_test, y_test),
  File "C:\Python310\lib\site-packages\wandb\integration\keras\keras.py", line 174, in new_v2
    return old_v2(*args, **kwargs)
  File "C:\Python310\lib\site-packages\wandb\integration\keras\keras.py", line 174, in new_v2
    return old_v2(*args, **kwargs)
  File "C:\Python310\lib\site-packages\wandb\integration\keras\keras.py", line 174, in new_v2
    return old_v2(*args, **kwargs)
  File "C:\Python310\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
    return fn(*args, **kwargs)
  File "C:\Python310\lib\site-packages\keras\engine\training.py", line 1747, in fit
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "C:\Python310\lib\site-packages\keras\callbacks.py", line 453, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "C:\Python310\lib\site-packages\wandb\integration\keras\keras.py", line 630, in on_epoch_end
    self._save_model_as_artifact(epoch)
  File "C:\Python310\lib\site-packages\wandb\integration\keras\keras.py", line 1032, in _save_model_as_artifact
    self.model.save(self.filepath[:-3], overwrite=True, save_format="tf")
  File "C:\Python310\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
    return fn(*args, **kwargs)
  File "C:\Python310\lib\site-packages\keras\engine\training.py", line 2826, in save
    saving_api.save_model(
  File "C:\Python310\lib\site-packages\keras\saving\saving_api.py", line 145, in save_model
    return legacy_sm_saving_lib.save_model(
  File "C:\Python310\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
    return fn(*args, **kwargs)
  File "C:\Python310\lib\site-packages\keras\saving\legacy\save.py", line 168, in save_model
    saved_model_save.save(
  File "C:\Python310\lib\site-packages\keras\saving\legacy\saved_model\save.py", line 98, in save
    saved_nodes, node_paths = save_lib.save_and_return_nodes(
  File "C:\Users\cosmi\AppData\Roaming\Python\Python310\site-packages\tensorflow\python\saved_model\save.py", line 1314, in save_and_return_nodes
    fingerprint_serialized = fingerprinting.CreateFingerprintDef(
122/122 [==============================] - 1s 7ms/step - loss: 0.0016 - mae: 0.0282 - mse: 0.0013 - val_loss: 0.0012 - val_mae: 0.0250 - val_mse: 0.0010 - lr: 0.0993
Epoch 8/150
 52/122 [===========>..................] - ETA: 0s - loss: 0.0013 - mae: 0.0258 - mse: 0.0011